// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: bkp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogRow mirrors store.LogRow.
type LogRow struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // RFC3339, UTC
	Project        string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	FilePath       string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileSize       int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	CompressedSize *int64                 `protobuf:"varint,5,opt,name=compressed_size,json=compressedSize,proto3,oneof" json:"compressed_size,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Error          string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs     int64                  `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Sha1           string                 `protobuf:"bytes,9,opt,name=sha1,proto3" json:"sha1,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogRow) Reset() {
	*x = LogRow{}
	mi := &file_bkp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRow) ProtoMessage() {}

func (x *LogRow) ProtoReflect() protoreflect.Message {
	mi := &file_bkp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRow.ProtoReflect.Descriptor instead.
func (*LogRow) Descriptor() ([]byte, []int) {
	return file_bkp_proto_rawDescGZIP(), []int{0}
}

func (x *LogRow) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogRow) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *LogRow) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *LogRow) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *LogRow) GetCompressedSize() int64 {
	if x != nil && x.CompressedSize != nil {
		return *x.CompressedSize
	}
	return 0
}

func (x *LogRow) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LogRow) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LogRow) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *LogRow) GetSha1() string {
	if x != nil {
		return x.Sha1
	}
	return ""
}

type InsertLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           *LogRow                `protobuf:"bytes,1,opt,name=row,proto3" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertLogRequest) Reset() {
	*x = InsertLogRequest{}
	mi := &file_bkp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertLogRequest) ProtoMessage() {}

func (x *InsertLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bkp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertLogRequest.ProtoReflect.Descriptor instead.
func (*InsertLogRequest) Descriptor() ([]byte, []int) {
	return file_bkp_proto_rawDescGZIP(), []int{1}
}

func (x *InsertLogRequest) GetRow() *LogRow {
	if x != nil {
		return x.Row
	}
	return nil
}

type InsertLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertLogResponse) Reset() {
	*x = InsertLogResponse{}
	mi := &file_bkp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertLogResponse) ProtoMessage() {}

func (x *InsertLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bkp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertLogResponse.ProtoReflect.Descriptor instead.
func (*InsertLogResponse) Descriptor() ([]byte, []int) {
	return file_bkp_proto_rawDescGZIP(), []int{2}
}

type GetLatestOKSHA1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestOKSHA1Request) Reset() {
	*x = GetLatestOKSHA1Request{}
	mi := &file_bkp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestOKSHA1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestOKSHA1Request) ProtoMessage() {}

func (x *GetLatestOKSHA1Request) ProtoReflect() protoreflect.Message {
	mi := &file_bkp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestOKSHA1Request.ProtoReflect.Descriptor instead.
func (*GetLatestOKSHA1Request) Descriptor() ([]byte, []int) {
	return file_bkp_proto_rawDescGZIP(), []int{3}
}

func (x *GetLatestOKSHA1Request) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type GetLatestOKSHA1Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha1          string                 `protobuf:"bytes,1,opt,name=sha1,proto3" json:"sha1,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestOKSHA1Response) Reset() {
	*x = GetLatestOKSHA1Response{}
	mi := &file_bkp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestOKSHA1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestOKSHA1Response) ProtoMessage() {}

func (x *GetLatestOKSHA1Response) ProtoReflect() protoreflect.Message {
	mi := &file_bkp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestOKSHA1Response.ProtoReflect.Descriptor instead.
func (*GetLatestOKSHA1Response) Descriptor() ([]byte, []int) {
	return file_bkp_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestOKSHA1Response) GetSha1() string {
	if x != nil {
		return x.Sha1
	}
	return ""
}

func (x *GetLatestOKSHA1Response) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ListLatestPerProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLatestPerProjectRequest) Reset() {
	*x = ListLatestPerProjectRequest{}
	mi := &file_bkp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLatestPerProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLatestPerProjectRequest) ProtoMessage() {}

func (x *ListLatestPerProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bkp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLatestPerProjectRequest.ProtoReflect.Descriptor instead.
func (*ListLatestPerProjectRequest) Descriptor() ([]byte, []int) {
	return file_bkp_proto_rawDescGZIP(), []int{5}
}

type ListLatestPerProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*LogRow              `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLatestPerProjectResponse) Reset() {
	*x = ListLatestPerProjectResponse{}
	mi := &file_bkp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLatestPerProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLatestPerProjectResponse) ProtoMessage() {}

func (x *ListLatestPerProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bkp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLatestPerProjectResponse.ProtoReflect.Descriptor instead.
func (*ListLatestPerProjectResponse) Descriptor() ([]byte, []int) {
	return file_bkp_proto_rawDescGZIP(), []int{6}
}

func (x *ListLatestPerProjectResponse) GetRows() []*LogRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

var File_bkp_proto protoreflect.FileDescriptor

const file_bkp_proto_rawDesc = "" +
	"\n" +
	"\tbkp.proto\x12\x06bkp.v1\"\x9f\x02\n" +
	"\x06LogRow\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12,\n" +
	"\x0fcompressed_size\x18\x05 \x01(\x03H\x00R\x0ecompressedSize\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x03R\n" +
	"durationMs\x12\x12\n" +
	"\x04sha1\x18\t \x01(\tR\x04sha1B\x12\n" +
	"\x10_compressed_size\"4\n" +
	"\x10InsertLogRequest\x12 \n" +
	"\x03row\x18\x01 \x01(\v2\x0e.bkp.v1.LogRowR\x03row\"\x13\n" +
	"\x11InsertLogResponse\"2\n" +
	"\x16GetLatestOKSHA1Request\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\"C\n" +
	"\x17GetLatestOKSHA1Response\x12\x12\n" +
	"\x04sha1\x18\x01 \x01(\tR\x04sha1\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x1d\n" +
	"\x1bListLatestPerProjectRequest\"B\n" +
	"\x1cListLatestPerProjectResponse\x12\"\n" +
	"\x04rows\x18\x01 \x03(\v2\x0e.bkp.v1.LogRowR\x04rows2\x85\x02\n" +
	"\n" +
	"BkpService\x12@\n" +
	"\tInsertLog\x12\x18.bkp.v1.InsertLogRequest\x1a\x19.bkp.v1.InsertLogResponse\x12R\n" +
	"\x0fGetLatestOKSHA1\x12\x1e.bkp.v1.GetLatestOKSHA1Request\x1a\x1f.bkp.v1.GetLatestOKSHA1Response\x12a\n" +
	"\x14ListLatestPerProject\x12#.bkp.v1.ListLatestPerProjectRequest\x1a$.bkp.v1.ListLatestPerProjectResponseB*Z(github.com/evbruno/bkp.go/internal/pb;pbb\x06proto3"

var (
	file_bkp_proto_rawDescOnce sync.Once
	file_bkp_proto_rawDescData []byte
)

func file_bkp_proto_rawDescGZIP() []byte {
	file_bkp_proto_rawDescOnce.Do(func() {
		file_bkp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bkp_proto_rawDesc), len(file_bkp_proto_rawDesc)))
	})
	return file_bkp_proto_rawDescData
}

var file_bkp_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_bkp_proto_goTypes = []any{
	(*LogRow)(nil),                       // 0: bkp.v1.LogRow
	(*InsertLogRequest)(nil),             // 1: bkp.v1.InsertLogRequest
	(*InsertLogResponse)(nil),            // 2: bkp.v1.InsertLogResponse
	(*GetLatestOKSHA1Request)(nil),       // 3: bkp.v1.GetLatestOKSHA1Request
	(*GetLatestOKSHA1Response)(nil),      // 4: bkp.v1.GetLatestOKSHA1Response
	(*ListLatestPerProjectRequest)(nil),  // 5: bkp.v1.ListLatestPerProjectRequest
	(*ListLatestPerProjectResponse)(nil), // 6: bkp.v1.ListLatestPerProjectResponse
}
var file_bkp_proto_depIdxs = []int32{
	0, // 0: bkp.v1.InsertLogRequest.row:type_name -> bkp.v1.LogRow
	0, // 1: bkp.v1.ListLatestPerProjectResponse.rows:type_name -> bkp.v1.LogRow
	1, // 2: bkp.v1.BkpService.InsertLog:input_type -> bkp.v1.InsertLogRequest
	3, // 3: bkp.v1.BkpService.GetLatestOKSHA1:input_type -> bkp.v1.GetLatestOKSHA1Request
	5, // 4: bkp.v1.BkpService.ListLatestPerProject:input_type -> bkp.v1.ListLatestPerProjectRequest
	2, // 5: bkp.v1.BkpService.InsertLog:output_type -> bkp.v1.InsertLogResponse
	4, // 6: bkp.v1.BkpService.GetLatestOKSHA1:output_type -> bkp.v1.GetLatestOKSHA1Response
	6, // 7: bkp.v1.BkpService.ListLatestPerProject:output_type -> bkp.v1.ListLatestPerProjectResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bkp_proto_init() }
func file_bkp_proto_init() {
	if File_bkp_proto != nil {
		return
	}
	file_bkp_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bkp_proto_rawDesc), len(file_bkp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bkp_proto_goTypes,
		DependencyIndexes: file_bkp_proto_depIdxs,
		MessageInfos:      file_bkp_proto_msgTypes,
	}.Build()
	File_bkp_proto = out.File
	file_bkp_proto_goTypes = nil
	file_bkp_proto_depIdxs = nil
}
