// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: bkp.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BkpService_InsertLog_FullMethodName            = "/bkp.v1.BkpService/InsertLog"
	BkpService_GetLatestOKSHA1_FullMethodName      = "/bkp.v1.BkpService/GetLatestOKSHA1"
	BkpService_ListLatestPerProject_FullMethodName = "/bkp.v1.BkpService/ListLatestPerProject"
)

// BkpServiceClient is the client API for BkpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BkpService exposes the backup_log SQLite store over gRPC.
type BkpServiceClient interface {
	InsertLog(ctx context.Context, in *InsertLogRequest, opts ...grpc.CallOption) (*InsertLogResponse, error)
	GetLatestOKSHA1(ctx context.Context, in *GetLatestOKSHA1Request, opts ...grpc.CallOption) (*GetLatestOKSHA1Response, error)
	ListLatestPerProject(ctx context.Context, in *ListLatestPerProjectRequest, opts ...grpc.CallOption) (*ListLatestPerProjectResponse, error)
}

type bkpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBkpServiceClient(cc grpc.ClientConnInterface) BkpServiceClient {
	return &bkpServiceClient{cc}
}

func (c *bkpServiceClient) InsertLog(ctx context.Context, in *InsertLogRequest, opts ...grpc.CallOption) (*InsertLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertLogResponse)
	err := c.cc.Invoke(ctx, BkpService_InsertLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bkpServiceClient) GetLatestOKSHA1(ctx context.Context, in *GetLatestOKSHA1Request, opts ...grpc.CallOption) (*GetLatestOKSHA1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestOKSHA1Response)
	err := c.cc.Invoke(ctx, BkpService_GetLatestOKSHA1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bkpServiceClient) ListLatestPerProject(ctx context.Context, in *ListLatestPerProjectRequest, opts ...grpc.CallOption) (*ListLatestPerProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLatestPerProjectResponse)
	err := c.cc.Invoke(ctx, BkpService_ListLatestPerProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BkpServiceServer is the server API for BkpService service.
// All implementations must embed UnimplementedBkpServiceServer
// for forward compatibility.
//
// BkpService exposes the backup_log SQLite store over gRPC.
type BkpServiceServer interface {
	InsertLog(context.Context, *InsertLogRequest) (*InsertLogResponse, error)
	GetLatestOKSHA1(context.Context, *GetLatestOKSHA1Request) (*GetLatestOKSHA1Response, error)
	ListLatestPerProject(context.Context, *ListLatestPerProjectRequest) (*ListLatestPerProjectResponse, error)
	mustEmbedUnimplementedBkpServiceServer()
}

// UnimplementedBkpServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBkpServiceServer struct{}

func (UnimplementedBkpServiceServer) InsertLog(context.Context, *InsertLogRequest) (*InsertLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertLog not implemented")
}
func (UnimplementedBkpServiceServer) GetLatestOKSHA1(context.Context, *GetLatestOKSHA1Request) (*GetLatestOKSHA1Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestOKSHA1 not implemented")
}
func (UnimplementedBkpServiceServer) ListLatestPerProject(context.Context, *ListLatestPerProjectRequest) (*ListLatestPerProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLatestPerProject not implemented")
}
func (UnimplementedBkpServiceServer) mustEmbedUnimplementedBkpServiceServer() {}
func (UnimplementedBkpServiceServer) testEmbeddedByValue()                    {}

// UnsafeBkpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BkpServiceServer will
// result in compilation errors.
type UnsafeBkpServiceServer interface {
	mustEmbedUnimplementedBkpServiceServer()
}

func RegisterBkpServiceServer(s grpc.ServiceRegistrar, srv BkpServiceServer) {
	// If the following call panics, it indicates UnimplementedBkpServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BkpService_ServiceDesc, srv)
}

func _BkpService_InsertLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BkpServiceServer).InsertLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BkpService_InsertLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BkpServiceServer).InsertLog(ctx, req.(*InsertLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BkpService_GetLatestOKSHA1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestOKSHA1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BkpServiceServer).GetLatestOKSHA1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BkpService_GetLatestOKSHA1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BkpServiceServer).GetLatestOKSHA1(ctx, req.(*GetLatestOKSHA1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _BkpService_ListLatestPerProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLatestPerProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BkpServiceServer).ListLatestPerProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BkpService_ListLatestPerProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BkpServiceServer).ListLatestPerProject(ctx, req.(*ListLatestPerProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BkpService_ServiceDesc is the grpc.ServiceDesc for BkpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BkpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bkp.v1.BkpService",
	HandlerType: (*BkpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertLog",
			Handler:    _BkpService_InsertLog_Handler,
		},
		{
			MethodName: "GetLatestOKSHA1",
			Handler:    _BkpService_GetLatestOKSHA1_Handler,
		},
		{
			MethodName: "ListLatestPerProject",
			Handler:    _BkpService_ListLatestPerProject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bkp.proto",
}
